name: Base Service CI

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

jobs:
  build_and_push:
    name: Build and deploy to Docker Hub and infrastructure repo
    runs-on: ubuntu-latest

    steps:


      # env:
      #   DOCKER_NAME_NO_TAG: '${{ secrets.DOCKER_HUB_URL }}/spotify-${{ inputs.service-name }}'

      - uses: actions/checkout@v3

      - name: Bump version and push tag
        id: tag_bump
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
          WITH_V: true

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag jakebriscoe-website:$(date +%s)

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      env:
        TEST: 'TEest'

      # env:
      #   Docker_Name_With_Tag: '$Docker_Name_No_Tag:${{ steps.tag_bump.outputs.tag }}'

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: $Docker_Full_Name , $Docker_Name_No_Tag:latest

      - name: Checkout infrastructure repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.INFRASTRUCTURE_REPO }}
          token: ${{ secrets.INFRASTRUCTURE_PAT }}
          path: ./infrastructure-repo

      - uses: mikefarah/yq@master

      - name: Push to infrastructure repo
        run: |
          cd infrastructure-repo

          yq -i '(.spec.template.spec.containers[].image | select(. == "$Docker_Name_No_Tag:v*")) = "$Docker_Full_Name"' *deployment*.yaml

          git config user.email "${{ secrets.AUTHOR_EMAIL }}"
          git config user.name "Github workflow"

          git add *deployment*.yaml
          git commit -m "Updated image version to ${{ steps.tag_bump.outputs.tag }} for ${{ github.event.repository.name }}"

          git push
