name: Content Service CI

on:
  push:
    branches:
      - main
    # paths:
    #   - "PACKAGE_PATH/**"

env:
  PACKAGE_PATH: packages/content-service

jobs:
  test:
    runs-on: ubuntu-latest
		steps:
			- run: echo "$PACKAGE_PATH"

  call-base-workflow:
    uses: ./.github/workflows/base-workflow.yaml
    secrets: inherit
    with:
      service-name: content-service
      package-path: "$PACKAGE_PATH"
