name: Content Service CI

on:
  push:
    paths:
      - "packages/content-service/**"

jobs:
  call-base-workflow:
    # try relative path
    uses: ${{ github.event.repository.name }}/.github/workflows/base-workflow.yaml
    secrets: inherit
    with:
      service-name: content-service
